### ISSUE TITLE
Registration desk

### ISSUE THREAD

**Issue by ccdesales** [SwissPy/swisspycon#32]
At least 3 people are needed at the registration desk. All volunteers are invited to chip in here.

**Comment by dbrgn** [comment]
There are multiple people in the helpers sheet that said they would do general stuff / entrance. That won't be a problem.

We could go through the list of people / helpers at the meeting, what do you think? That would probably be most productive. And then send them an e-mail to confirm whether they can help.

**Comment by chiesax** [comment]
Yes lets contact them. But I suggest we define the tasks of ALL helpers.
- one or two persons to help the speakers with the beamer, computer etc. and manage the talks duration, introduce the speaker. He will also make a copy of the presentation so that we may later publish it.
- one person to manage video recording of the talks
- any other?

Then we send an email with the tasks description..

**Comment by dbrgn** [comment]
Yeah, but I'd do that during the program meeting :) Easier to do than asynchronously via Github.

**Comment by sfkeller** [comment]
Currently you planned to open registration 08:30 until 09:15. In my experience, this time frame should be extended in both directions. I would plan to open at 08:00 until 10:00. We don't necessarily have to change this in the programm; this is just an internal hint.

**Comment by dbrgn** [comment]
The problem with this is that the people at the registration desk cannot attend the first talks...

@sfkeller maybe two of your interns could take over as soon as the talks start (around 9:00 until 10:00)?

**Comment by sfkeller** [comment]
Yes, they can. Pls. schedule Mike and Joël for this task.

**Comment by dbrgn** [comment]
Great! :)

**Comment by dbrgn** [comment]
Worked out nicely. @loleg even paid in bitcoin ;)
