### ISSUE TITLE
Closing Presentation

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/swisspycon#61]
Will be done by @href and @jacinda.

What should be included?
- Thank everyone for attending
- Thank all the helpers and sponsors
- Talk about social event
- Quick presentation by Beekeeper (Sponsor Socialevent)
- In case next year will be organized again, people should check the website. Call for organizers.

**Comment by jakeret** [comment]
give information about key signing event #24

**Comment by href** [comment]
I thought I didn't do this one :)
I can prepare a small presentation for this though, no problem. Unless you want to do it @jacinda?

What's the quick presentation by Beekeeper? Is that a separate presentation that comes first?

**Comment by dbrgn** [comment]
Not sure, that was what we wrote down in the [meeting notes](https://etherpad.coredump.ch/p/sps16-meeting-notes) :)

> What's the quick presentation by Beekeeper? Is that a separate presentation that comes first?

They'll get about 3 minutes to present their company, because they're a sponsor. Their slot is in the afternoon (makes sense I guess, shortly before the social event) and Divio's slot is in the morning.

**Comment by href** [comment]
Do we want them to be sandwiched in the closing presentation? Or have them do it before that? The last word should be ours in any case.

**Comment by dbrgn** [comment]
Yep. I'd put them in the ending presentation (not at the very end though). The best moment would probably be after saying some words about the social event (à la "and now a word from our sponsors").

**Comment by href** [comment]
Ok this is what I have in mind.

I would suggest we let Beekeeper go first, to not make it too much of a fragmented affair. We will introduce Beekeeper quickly ("Before the final presentation, a word from one of our sponsors").

After that we do the final presentation. Otherwise I predict hangups with switching presentations and so on. It's still a sandwich but the top layer is super thin ;)

After that, do something like this:
[finalpresentation.pdf](https://github.com/SwissPy/swisspycon/files/101815/finalpresentation.pdf)

As you can see I still need:
- [ ] Infos about the after party
- [ ] Infos about the key signing event

Let me know what we should convey in this regard during the final presentation.

Also, I need SVG logos from Divio and Beekeeper.

**Comment by href** [comment]
@chiesax wrote in the thread I accidentally hijacked:

The sandwich idea sounds good!

I also like the presentation. Super slim – people anyway prefer to go to the party instead of hearing another talk ;-)

Maybe it would be good to have our official logo somewhere (the one with the snakes from the poster)

**Comment by href** [comment]
I totally wrote this into the wrong thread. I moved everything here to get some order back.

> Maybe it would be good to have our official logo somewhere (the one with the snakes from the poster)

I think I could add it to the last slide. I don't want to put it everywhere because everyone's gonna have it around their necks anyway.

**Comment by href** [comment]
Actually the logo goes kind of well with the mountains:

![screenshot of keynote 23-01-16 16-11-25](https://cloud.githubusercontent.com/assets/273163/12530846/fc5825d2-c1eb-11e5-904d-b3be3a4ca43d.png)

**Comment by jacinda** [comment]
Sorry - missed this thread.  @href - I think you should go ahead and do it since I already have another talk, but if there's something you'd like me to say I'm happy to.

**Comment by href** [comment]
I can do it no problem.

**Comment by dbrgn** [comment]
If you have any comments for potential future closing presentations, leave them here.
