### ISSUE TITLE
Report and photos

### ISSUE THREAD

**Issue by sfkeller** [SwissPy/swisspycon#67]
I'd like to make a short report with few sentences and ~2 photos from the event.
This will be published at news page of HSR website: www.hsr.ch/news .
Does anyone want's to make and share photos?
Anyone volunteering to write some pickings about the event to be offered to news agencies?

**Comment by dbrgn** [comment]
I can bring my camera and take a few pictures during the event.

**Comment by href** [comment]
I can write a short report - I occasionally do this sort of thing. I'm assuming you need it in both German and English? How many words do you require?

I suggest I write the report on Saturday and post it here.

**Comment by href** [comment]
@sfkeller Let me know if you still require a report as well as the parameters of it (languages, words).

**Comment by sfkeller** [comment]
@href: Ah, yes pls. if you have time. I'm recovering now until 18h today :-)

**Comment by href** [comment]
I can, but I do need to know the word count and language(s) ;-)

**Comment by sfkeller** [comment]
For my own purposes it's "vier bis fünf Sätze Zusammenfassung und 1 bis 2 Fotos". But what I would propose for our common usage, that's a report of about 700 characters in english, german and french.

**Comment by href** [comment]
Alright. I'll whip something up. Pass on the French though.

**Comment by href** [comment]
Let me know how this is like. I wrote it in German first, I'll add English later. It's a bit longer because 700 characters is like 5 tweets ;)

Also does anyone know the name of the instrument that Matthieu was playing in the videos?

---

**Fliegende Drohnen, Live Musik und Python**

Am ersten Swiss Python Summit präsentierten Musiker, Entwickler und Forscher Ihre Arbeit im Zusammenhang mit der Programmiersprache Python. Die 114 Teilnehmer und Teilnehmerinnen lernten die Sprache besser kennen, bekamen die neuesten Werkzeuge demonstriert und erweiterten Ihren Horizont an der HSR in Rapperswil.

**Dunkle Materie und Drohnen**

Dr. Chihway Chang vom Institut für Astronomie an der ETH Zürich vermittelte einen faszinierenden Eindruck in die Erforschung des Universums. Python, so stellt sich heraus, kommt in der Astrophysik vermehrt zum Einsatz. Das simple Design der Sprache und die grosser Verfügbarkeit von freien Softwarebibliotheken sind nur einige der Gründe für diese wachsende Popularität.

**Live Musik - von Python beeinflusst**

Als Teil des Projekts “Les Chemins de Traverse” nutzt Matthieu Amiguet Python dazu, die Musik des Ensembles Live zu verändern. Da kann es schon passieren, dass sich eine Bassflöte plötzlich wie ein Alphorn anhört. Das und anderes demonstrierte Matthieu im vollen Hörsaal.

**Erweiterte Horizonte**

Ganze 9 Vorträge zu vielen anderen interessanten Themen hielten die Besucher des allerersten Swiss Python Summit bei Laune. Es war ein gelungener Anlass an dem noch so mancher gestandener Entwickler ganz viel lernen konnte.

**Comment by chiesax** [comment]
I can handle french and italian...

**Comment by sfkeller** [comment]
@href 

> Also does anyone know the name of the instrument that Matthieu was playing in the videos? 

Was it Bass flute, flûte basse, Bassflöte ?

**Comment by jacinda** [comment]
I also remember bass flute.

**Comment by chiesax** [comment]
http://www.lescheminsdetraverse.net/artistes/matthieu-amiguet/

**Comment by chiesax** [comment]
flûte basse

**Comment by chiesax** [comment]
https://fr.wikipedia.org/wiki/Fl%C3%BBte_basse

**Comment by chiesax** [comment]
https://en.wikipedia.org/wiki/Bass_flute

**Comment by chiesax** [comment]
@sposs: since french is your mother tongue...

**Comment by dbrgn** [comment]
Nice! :)

> 140 TeilnehmerInnen

That was 114 iirc.

 Also, I'd write `Teilnehmerinnen und Teilnehmer`, looks a bit less awkward.

> Institut für Astronomie

To be precise it would be the "Cosmology Research Group", but that's part of the institute :)

> Als Teil des Projekts “Les Chemins de Traverse” nutzt Matthieu Amiguet Python dazu die Musik des Ensembles Live zu verändern.

I think some commas are missing here. Same thing in the next sentence, a comma missing before `dass`.

**Comment by href** [comment]
Thanks @dbrgn I applied your suggestions. I will leave the institute because the target audience is the lay person and I wanted to keep the text as German sounding as possible (otherwise I wouldn't use "Softwarebibliotheken" ;).

And now for the English translation:

---

**Flying Drones, Live Music and Python**

Musicians, software developers and researchers presented their work and its relation to the programming language Python at the first Swiss Python Summit. 114 attendees learned more about the language, watched demonstrations about the latest tools and broadened their horizons at HSR in Rapperswil on February the 5th.

**Dark Matter and Drones**

Dr. Chihway Chang of the Cosmology Research Group at ETH Zürich gave a fascinating account of her work. Python, as it turns out, is being used increasingly often in astrophysics. Python’s simple design and the large number of freely available software libraries are key reasons for its rising popularity in academia.

**Live Music with Python**

As part of the Neuchâtel based group “Les Chemins de Traverse” Matthieu Amiguet uses Python to change the live sound of his musical ensemble. A bass flute suddenly sounds like an alphorn - an effect which Matthieu was more than happy to demonstrate to the full auditorium.

**Horizons Broadened**

A total of 9 talks about various interesting topics kept the attendees on the edge of their seats. The first Swiss Python Summit was a well received conference where even the most seasoned developer could learn a lot of new things.

**Comment by chiesax** [comment]
I would rather say that "Les Chemins de Traverse" is a group of artists rather than a project. You may want to add that they are based in Neuchâtel (to show the genuine swissness of the event).

"the large number of available **free** software libraries" to be more complete.

A sentence about Drones?

**Comment by chiesax** [comment]
Is "developer" a well understood world outside of the tech realm?
Should it not rather be "software developer" or "programmer"?

**Comment by href** [comment]
Good points. Updated.

**Comment by chiesax** [comment]
What about starting with something fancy like: "Python: thats not only a dangerous snake but one of the most popular programming languages around the world"...

**Comment by chiesax** [comment]
By the way do you know how we could submit this to swiss new agencies for free?

**Comment by chiesax** [comment]
I also think the date of the event should be mentioned somewhere...

**Comment by href** [comment]
+1 on the date, -1 on the different intro on the basis of "too many cooks". But feel free to rewrite the whole thing, I'm not particularly attached to my articles ;)

Also, since this is for HSRs internal news page (and written for that audience) I would suggest that HSR notifies the press through their channels. I'm assuming they have someone that does that kind of thing.

**Comment by sfkeller** [comment]
@href: Thanks for the text! I fear that our HSR media team is not well prepared for promoting such IT events, since they somehow focus on student acquisition and regional-organizational issues. And I'm rather busy next week.

I've nevertheles entered now following short text to eventbooster.ch. They promote this event to several news papers, but I'm not sure how kee "regular" journalists for such events (I'm curious myself): 

> Am ersten Swiss Python Summit präsentierten vergangenen Freitag Musiker, Entwickler und Forscher Ihre Arbeit im Zusammenhang mit der Programmiersprache Python an der HSR Hochschule für Technik in Rapperswil. Die 114 Teilnehmer und Teilnehmerinnen lernten die Computer-Sprache besser kennen, bekamen die neuesten Werkzeuge demonstriert und erweiterten Ihren Horizont. Insgesamt neun Vorträge zu verschiedenen Themen hielten die Besucher des allerersten Swiss Python Summit bei Laune. Es war ein gelungener Anlass an dem noch so mancher gestandener Entwickler ganz viel dazu lernen konnte. Der nächste IT-Event an der HSR ist bereits geplant und zwar die Tagung Swiss PGDay bei der es um die freie Datenbank Postgres geht.

I assume you know Google+ and Facebook which often serve as news accelerators (but which I don't use myself). 

Here's an incomplete list of potential press release candidates: ossdirectory.com/opensource.ch, inside-it.ch, Netzwoche.ch and 20min.ch . The first one, http://www.ossdirectory.com/ is the easiest, since you can submit a text (would be e.g. in de/fr/en) and then they put it online and distribute it on Wednesday, 12 o'clock in their "Wöchentlicher www.opensource.ch Newsletter".

For inside-it.ch, Netzwoche.ch and 20min.ch (and HSR news) and the like, it's essential to have some nice photos.

**Comment by sfkeller** [comment]
Use Flickr or Pinterest (with tag #pysummit16 ) as photo sharing website?

**Comment by chiesax** [comment]
**Drones volants, musique en direct et Python**

Musiciens, programmeurs et chercheurs ont présenté leur travail en relation avec la langage informatique Python à la première édition du Swiss Python Summit. Les 114 participants ont pu perfectionner leurs connaissances tout en s'amusant à la Haute Ecole Technique de Rapperswil.

**Matière obscure et Drones**

Le Dr. Chihway Chang du groupe de recherche cosmologique de l'EPF Zurich a présenté un résumé fascinant de son travail. Le langage Python est de plus en plus utilisé dans la recherche scientifique. Les clefs de son succès sont la simplicité d'utilisation et le grand nombre de librairies gratuites disponibles.

**Musique en direct avec Python**

Matthieu Amiguet du groupe artistique « Les Chemins de Traverse » de Neuchâtel utilise Python pour changer en direct le son d'un instrument musical. Tout à coup, sa flûte basse raisonne comme un cor des Alpes. Matthieu a aussi donné une démonstration aux auditeurs de la salle bondée.

**Élargir ses horizons**

Au total 9 présentations remarquables aux sujets variés ont maintenu les auditeurs bien collés à leur chaises. La première conférence Suisse Python a été un grand succès ou les plus expert des développeurs ont pleinement profité et le novice ne s'est pas senti exclu.

**Comment by href** [comment]
> I assume you know Google+ and Facebook which often serve as news accelerators (but which I don't use myself).

Who does? ;)

I think we could send it to inside-it.ch by mail (I don't think they require pictures). General public news like 20min.ch are probably not interested, nor is this channel interesting for us. It might be nice to have for HSR, but the Python Summit is fine without that imho.

Can you maybe send the texts we have to inside-it.ch through your HSR mail account @sfkeller? That would make it look a bit more official. The e-mail is redaktion@inside-it.ch.

Ultimately I think this can just be put on the HSR news site though once we have some pictures. That was the original goal as far as I'm concerned and lack of publicity has not been a concern for us so far. 

I also have yet to find out about any kind of tech conference through old media. Twitter, techup.ch and Python's Weekly newsletter is where I would've found out about Python Summit if I wasn't in the org team. Or is this just me?

**Comment by sfkeller** [comment]
> Can you maybe send the texts we have to inside-it.ch through your HSR mail account @sfkeller?

Yes, I can do that as soon as I have pictures. I've made some snapshots but there are probably more from you to share?

**Comment by href** [comment]
My phone snapshots are not up to snuff I'm afraid.

**Comment by jacinda** [comment]
For the "Live Music with Python" section I would change the last two
sentences to:

A bass flute suddenly sounds like an alphorn - an effect which Matthieu was
more than happy to demonstrate to the full auditorium.

It sounds a bit more natural in English this way.

Jacinda

**Comment by chiesax** [comment]
> For inside-it.ch, Netzwoche.ch and 20min.ch (and HSR news) and the like, it's essential to have some nice photos.

Well, as for the nice pictures, we already have our awesome logo ;-)

**Comment by dbrgn** [comment]
> I've made some snapshots but there are probably more from you to share?

Unfortunately I forgot to bring my camera :(

**Comment by href** [comment]
> It sounds a bit more natural in English this way.

Thanks, updated.

**Comment by jakeret** [comment]
Since you mentioned Dr. Chang so prominently I will try to publish the text somewhere here at ETH as well. Hope this is ok for you

**Comment by href** [comment]
Sure, I hereby publish the text under the [WTFPL](https://en.wikipedia.org/wiki/WTFPL)

**Comment by sfkeller** [comment]
There's the (german) news at HSR website: http://bit.ly/swiss-python-summit-16-hsr-news . 

Sorry that there's originally no search-engine friendly weblink. I've slightly adapted the text (especially mentioning also Amiguet's "Künstlergruppe". Finally I was free to mention PGDay.ch :-). 

Just one thing is missing: At the time when the videos are published, we could mention this too.

**Comment by ccdesales** [comment]
The report and the pictures have been published. Please reopen if you consider there are still pending items.
